server:
  port: ${server-port:9000}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${database-name:project_test}
    username: ${database-username:root}
    password: ${database-password:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
