server:
  port: ${server-port}
spring:
  datasource:
    url: ${database-url}/${database-name}
    username: ${database-username}
    password: ${database-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: ${show-sql}
